#!/bin/sh

set -e

TUNIERP_CONFIGURATION_FILE=/etc/tunierp/openerp-server.conf
TUNIERP_GROUP="tunierp"
TUNIERP_DATA_DIR=/var/lib/tunierp
TUNIERP_LOG_DIR=/var/log/tunierp
TUNIERP_USER="tunierp"

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^tunierp:"; then
            adduser --system --home $TUNIERP_DATA_DIR --quiet --group $TUNIERP_USER
        fi
        # Register "$TUNIERP_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $TUNIERP_USER" 2> /dev/null || true
        # Configuration file
        chown $TUNIERP_USER:$TUNIERP_GROUP $TUNIERP_CONFIGURATION_FILE
        chmod 0640 $TUNIERP_CONFIGURATION_FILE
        # Log
        mkdir -p $TUNIERP_LOG_DIR
        chown $TUNIERP_USER:$TUNIERP_GROUP $TUNIERP_LOG_DIR
        chmod 0750 $TUNIERP_LOG_DIR
        # Data dir
        chown $TUNIERP_USER:$TUNIERP_GROUP $TUNIERP_DATA_DIR
        # update-python-modules NOW otherwise invoke-rc.d openerp start will fail
        update-python-modules
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
