#!/bin/sh

set -e

TUNIERP_LIB_DIR=/var/lib/tunierp
TUNIERP_USER="tunierp"
TUNIERP_GROUP="tunierp"

case "${1}" in
    remove)
        deluser --quiet --system $TUNIERP_USER || true
        delgroup --quiet --system --only-if-empty $TUNIERP_GROUP || true
        if [ -d "$TUNIERP_LIB_DIR" ]; then
            rm -rf $TUNIERP_LIB_DIR
        fi
        ;;

    purge)
        if [ -d "$TUNIERP_LIB_DIR" ]; then
            rm -rf $TUNIERP_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
